apiVersion: operator.gatekeeper.sh/v1alpha1
kind: Gatekeeper
metadata:
  labels:
    app: gatekeeper
  name: gatekeeper
spec:
  audit:
    auditChunkSize: 500
    auditFromCache: Enabled
    constraintViolationLimit: 20
    emitAuditEvents: Enabled
    logLevel: INFO
    replicas: 1
    resources:
      limits:
        cpu: 300m
        memory: 600Mi
      requests:
        cpu: 300m
        memory: 600Mi
  mutatingWebhook: Enabled
  validatingWebhook: Enabled
  webhook:
    emitAdmissionEvents: Enabled
    logLevel: INFO
    replicas: 1

